'use strict';
const $=id=>document.getElementById(id);let state=Panel.initial(),selected=state.ports[0].id;
try{const saved=localStorage.getItem('patchlab-v1');if(saved)state=Panel.validate(JSON.parse(saved));}catch(e){console.warn('Saved project could not be restored',e);}selected=state.ports[0]?.id;
const batchSelection=new Set();let rearView=false;
const globalFields=['name','format','units','rackUnits','width','height','thickness','mounts','inset','mountDiameter','bodyColor','labelColor','fontSize','inlay','bed','autoSplit','bedMargin','fitClearance','reinforce','ribDepth','ribWidth','hardwareClearance'];
function persist(){try{localStorage.setItem('patchlab-v1',JSON.stringify(state));$('saved').textContent='● Saved locally';}catch{$('saved').textContent='Save project to keep changes';}}
function draw(){persist();$('rackUnitsField').hidden=state.units!=='rack';drawGaps();const ears=Panel.rackEars(state);$('earSummary').textContent=ears.depth?'Solid rack ears: '+Number(ears.total.toFixed(2))+' mm total thickness, '+Number(ears.width.toFixed(2))+' mm wide. Flat backing supports the screw clamping area. Connector faces stay '+state.thickness+' mm thick.':'Rack ears use the panel face thickness.';$('projectTitle').textContent=state.name||'Untitled panel';$('dimensions').textContent=`${state.width} × ${state.height} × ${state.thickness} mm`; $('size').textContent=`${state.width} × ${state.height} mm`;$('count').textContent=String(state.ports.length).padStart(2,'0');$('portCount').textContent=`/ ${state.ports.length}`;$('preview').innerHTML=rearView?Panel.rearSvg(state):Panel.svg(state,selected);const plan=Panel.splitPlan(state);$('splitSummary').textContent=plan.error?plan.error:plan.seams.length?plan.segments.length+' printable sections: '+plan.segments.map(p=>p.width.toFixed(1)+' mm').join(' + ')+' | '+plan.seams.length+' snap key(s). Dashed lines mark seams; shaded strips show rear joint zones.':'One-piece panel.';const issues=Panel.warnings(state);$('warnings').innerHTML=issues.length?issues.map(w=>`<div class="warning">${Panel.esc(w)}</div>`).join(''):'<div class="good">✓ Layout checks passed · Verify connector fit before printing.</div>';$('ports').innerHTML=state.ports.length?state.ports.map((p,i)=>`<div class="port ${p.id===selected?'selected':''} ${batchSelection.has(p.id)?'batch-selected':''}"><input type="checkbox" data-select="${p.id}" aria-label="Select port ${i+1}: ${Panel.esc(p.label||'Unnamed port')}" ${batchSelection.has(p.id)?'checked':''}><button class="port-main" data-port="${p.id}"><span class="number">${String(i+1).padStart(2,'0')}</span><strong>${Panel.esc(p.label||'Unnamed port')}</strong><span class="shape">${Panel.esc(Panel.presets[p.type].name)}</span><span class="edit">Edit &#8599;</span></button></div>`).join(''):'<p class="muted">Your blank canvas is ready. Add your first connector.</p>';updateBatchControls();}

function sync(){for(const k of globalFields){if($(k).type==='checkbox')$(k).checked=state[k];else $(k).value=state[k];}draw();editor();}
function numberField(p,key,label,min,max,step=.1){return `<label>${label}<input data-field="${key}" type="number" required value="${p[key]}" min="${min}" max="${max}" step="${step}"></label>`;}
function editor(){const p=state.ports.find(p=>p.id===selected);$('selectedTitle').textContent=p?`Port ${String(state.ports.indexOf(p)+1).padStart(2,'0')}`:'No connector selected';if(!p){$('editor').innerHTML='<p class="muted">Add a connector to get started.</p>';return;}$('editor').innerHTML=`<label>Connector template<select data-field="type">${Object.entries(Panel.presets).map(([k,v])=>`<option value="${k}" ${p.type===k?'selected':''}>${v.name}</option>`).join('')}</select></label><label>Port name<input data-field="label" maxlength="40" value="${Panel.esc(p.label)}"></label><div class="pair">${numberField(p,'x','Center X · mm',0,state.width)}${numberField(p,'y','Center Y · mm',0,state.height)}</div><div class="pair">${numberField(p,'w',p.shape==='circle'?'Diameter · mm':'Width · mm',1,200)}${p.shape==='rect'?numberField(p,'h','Height · mm',1,200):numberField(p,'rotation','Rotation · °',-180,180,1)}</div>${p.shape==='rect'?numberField(p,'rotation','Rotation · °',-180,180,1):''}${numberField(p,'maxThickness','Mounting limit mm (0 = unknown)',0,12)}${numberField(p,'labelY','Label center Y · mm',0,state.height)}<p class="note">Position measured from the upper-left corner. Label stays horizontal.</p><label class="check"><input data-field="screws" type="checkbox" ${p.screws?'checked':''}> Diagonal mounting screws</label>${p.screws?`<div class="pair">${numberField(p,'sx','Spacing X · mm',0,100)}${numberField(p,'sy','Spacing Y · mm',0,100)}</div>${numberField(p,'sd','Screw hole Ø · mm',1,12)}`:''}<div class="actions"><button id="duplicate">Duplicate</button><button id="remove" class="danger">Remove</button></div>`;
$('duplicate').onclick=()=>{if(state.ports.length>=100)return;const q=JSON.parse(JSON.stringify(p));q.id=nextId();q.x=Math.min(state.width-25,p.x+35);q.label=p.label.slice(0,33)+' COPY';state.ports.push(q);selected=q.id;draw();editor();};$('remove').onclick=()=>{state.ports=state.ports.filter(q=>q.id!==p.id);selected=state.ports[0]?.id;draw();editor();};}
function nextId(){return Math.max(0,...state.ports.map(p=>p.id))+1;}
for(const key of globalFields)$(key).addEventListener('change',()=>{const el=$(key);if(!el.checkValidity()){el.reportValidity();return;}state[key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(key==='format'&&state.format!=='custom'){state.width=state.format==='19'?482.6:254;arrangeRows();}if(key==='width')state.format='custom';if(key==='units'&&state.units!=='custom'){if(state.units!=='rack')state.rackUnits=Number(state.units);state.height=Number((state.rackUnits*44.45-.8).toFixed(2));}if(key==='rackUnits'){state.units='rack';state.height=Number((state.rackUnits*44.45-.8).toFixed(2));}if(key==='height')state.units='custom';sync();});
function editPort(e){const k=e.target.dataset.field,p=state.ports.find(p=>p.id===selected);if(!k||!p)return;if(!e.target.checkValidity()){e.target.reportValidity();return;}if(k==='type'){Object.assign(p,Panel.presets[e.target.value],{type:e.target.value});}else p[k]=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value;draw();if(k==='type'||k==='screws')editor();}
$('editor').addEventListener('input',editPort);$('editor').addEventListener('change',editPort);
$('name').addEventListener('input',()=>{state.name=$('name').value;draw();});
function select(e){const item=e.target.closest('[data-port]');if(!item)return;selected=+item.dataset.port;draw();editor();} $('ports').addEventListener('click',select);$('preview').addEventListener('click',select);$('preview').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(e);}});
$('add').onclick=()=>{if(state.ports.length>=100){alert('Maximum 100 ports per project.');return;}const p=Panel.port(nextId(),state.width/2);p.label=`PORT ${String(state.ports.length+1).padStart(2,'0')}`;state.ports.push(p);selected=p.id;arrangeRows();draw();editor();};$('arrange').onclick=()=>{arrangeRows();draw();editor();};
function download(text,ext,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=(state.name.replace(/[^a-z0-9_-]+/gi,'-')||'panel')+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('save').onclick=()=>download(JSON.stringify(state,null,2),'json','application/json');$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('Project file is too large.');const incoming=Panel.validate(JSON.parse(await file.text()));state=incoming;batchSelection.clear();selected=state.ports[0]?.id;sync();}catch(err){alert('Could not open project: '+err.message);}e.target.value='';};
$('export').onclick=()=>{$('exportWarnings').innerHTML=Panel.warnings(state).map(w=>`<div class="warning">${Panel.esc(w)}</div>`).join('');const plan=Panel.splitPlan(state);$('splitExport').innerHTML=plan.seams.length?'<h3>Split-panel export</h3><p>Set <code>segment = 1</code> through <code>'+plan.segments.length+'</code>, exporting body and labels for each. Each pair shares coordinates and is already oriented face-down for printing.</p><p>Set <code>part = "key"</code> and print '+plan.seams.length+' copy/copies. First try <code>part = "coupon"</code> for two joint samples and a short key. Slide the key up from the lower edge until its tongue clicks into the rear pocket. Press the tongue into the backing opening to release.</p><p class="note">Prototype joint; strength and latch life need physical testing. Rear connector bodies and cable clearance are not modeled.</p>':state.reinforce?'<p>Rear ribs enabled: body and labels export face-down with shared coordinates. Mounting areas retain the configured face thickness.</p>':'';$('scadExport').disabled=!!plan.error;stlExporter.refresh();$('exportDialog').showModal();};$('close').onclick=()=>$('exportDialog').close();$('scadExport').onclick=()=>{if(state.inlay>=state.thickness){alert('Reduce inlay depth below panel thickness before exporting.');return;}try{download(Panel.scad(state),'scad','text/plain');}catch(err){alert(err.message);}};$('svgExport').onclick=()=>download(Panel.svg(state,null,true),'svg','image/svg+xml');sync();

function updateBatchControls(){
 for(const id of batchSelection)if(!state.ports.some(p=>p.id===id))batchSelection.delete(id);
 const count=batchSelection.size;
 $('selectionCount').textContent=count+' selected';
 $('selectAll').checked=count>0&&count===state.ports.length;
 $('selectAll').indeterminate=count>0&&count<state.ports.length;
 $('selectAll').disabled=!state.ports.length;
 for(const id of ['clearSelection','editSelected','deleteSelected'])$(id).disabled=!count;
}
$('ports').addEventListener('change',e=>{if(!e.target.matches('[data-select]'))return;const id=Number(e.target.dataset.select);if(e.target.checked)batchSelection.add(id);else batchSelection.delete(id);e.target.closest('.port').classList.toggle('batch-selected',e.target.checked);updateBatchControls();});
$('selectAll').onchange=e=>{batchSelection.clear();if(e.target.checked)state.ports.forEach(p=>batchSelection.add(p.id));draw();};
$('clearSelection').onclick=()=>{batchSelection.clear();draw();};
$('deleteSelected').onclick=()=>{state.ports=state.ports.filter(p=>!batchSelection.has(p.id));if(batchSelection.has(selected))selected=state.ports[0]?.id;batchSelection.clear();draw();editor();};
$('editSelected').onclick=()=>{$('batchForm').reset();$('batchTitle').textContent='Edit '+batchSelection.size+' selected ports';$('batchError').textContent='';$('batchDialog').showModal();};
$('closeBatch').onclick=$('cancelBatch').onclick=()=>$('batchDialog').close();
$('batchForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),patch={};for(const [key,value]of data){if(value==='')continue;patch[key]=['type','label'].includes(key)?value:key==='screws'?value==='true':Number(value);}try{state=Panel.batchEdit(state,[...batchSelection],patch);draw();editor();$('batchDialog').close();}catch(err){$('batchError').textContent=err.message;}};

$('toleranceExport').onclick=()=>download(Panel.scad(state,'tolerance'),'scad','text/plain');

$('viewToggle').onclick=()=>{rearView=!rearView;$('viewToggle').textContent=rearView?'Show front':'Show rear';$('viewTitle').textContent=rearView?'REAR VIEW - RIBS & CHANNELS':'FRONT VIEW';draw();};

for(const key of globalFields){const el=$(key);if(!['number','color'].includes(el.type))continue;el.addEventListener('input',()=>{if(!el.checkValidity())return;state[key]=el.type==='number'?Number(el.value):el.value;if(key==='rackUnits'){state.units='rack';state.height=Number((state.rackUnits*44.45-.8).toFixed(2));$('height').value=state.height;$('units').value='rack';}if(key==='width'){state.format='custom';$('format').value='custom';}if(key==='height'){state.units='custom';$('units').value='custom';}draw();});}

const stlExporter=STLExport.init(()=>state);

let layoutUndo=null;
function drawGaps(){$('spacingGaps').innerHTML=Layout.gaps(state).map(g=>'<label class="gap-editor">'+Panel.esc(g.left.label||'Port '+g.left.id)+' to '+Panel.esc(g.right.label||'Port '+g.right.id)+'<span>Gap <input data-gap="'+g.right.id+'" type="number" min="0" step="0.1" value="'+g.gap+'"> mm | centers '+g.pitch+' mm</span></label>').join('')||'<p class="note">Place two ports at the same center Y to edit their gap.</p>';}
function applyLayout(action){try{const next=action();layoutUndo=structuredClone(state);state=next;$('undoLayout').disabled=false;$('layoutError').textContent='';batchSelection.clear();if(!state.ports.some(p=>p.id===selected))selected=state.ports[0]?.id;sync();}catch(e){$('layoutError').textContent=e.message;}}
$('applySpacing').onclick=()=>{if(!$('spacingDistance').reportValidity())return;applyLayout(()=>Layout.horizontal(state,[...batchSelection],$('spacingMode').value,Number($('spacingDistance').value),$('rowAlign').value));};
$('stackRows').onclick=()=>{if(!$('stackCount').reportValidity())return;applyLayout(()=>Layout.stack(state,selected,Number($('stackCount').value)));};
$('spacingGaps').onchange=e=>{if(!e.target.matches('[data-gap]')||!e.target.reportValidity())return;applyLayout(()=>Layout.setGap(state,Number(e.target.dataset.gap),Number(e.target.value)));};
$('undoLayout').onclick=()=>{if(!layoutUndo)return;state=layoutUndo;layoutUndo=null;batchSelection.clear();selected=state.ports[0]?.id;$('undoLayout').disabled=true;$('layoutError').textContent='';sync();};

function arrangeRows(){for(const row of Layout.rows(state.ports))Panel.arrange({...state,ports:row.ports});}
