(function(root){
'use strict';
const P=typeof module!=='undefined'?require('./model.js'):root.Panel;
const round=x=>Math.round(x*10000)/10000;
function bounds(p){const boxes=P.cutouts(p).map(c=>{const a=c.rotation*Math.PI/180,w=c.shape==='circle'?c.w:Math.abs(c.w*Math.cos(a))+Math.abs(c.h*Math.sin(a));return {left:c.x-w/2,right:c.x+w/2};});return {left:Math.min(...boxes.map(b=>b.left)),right:Math.max(...boxes.map(b=>b.right))};}
function rows(ports){const result=[];for(const p of [...ports].sort((a,b)=>a.y-b.y||a.x-b.x)){let row=result.find(r=>Math.abs(r.y-p.y)<.05);if(!row){row={y:p.y,ports:[]};result.push(row);}row.ports.push(p);}for(const r of result)r.ports.sort((a,b)=>a.x-b.x);return result;}
function gaps(s){return rows(s.ports).flatMap(r=>r.ports.slice(1).map((p,i)=>({left:r.ports[i],right:p,gap:round(bounds(p).left-bounds(r.ports[i]).right),pitch:round(p.x-r.ports[i].x)})));}
function checked(s){P.validate(s);for(const p of s.ports){const b=bounds(p);if(b.left<0||b.right>s.width)throw Error('This spacing puts a cutout outside the panel. Reduce spacing or use a wider panel.');}return s;}
function setGap(s,rightId,value){if(!Number.isFinite(value)||value<0)throw Error('Gap must be zero or greater.');const next=structuredClone(s),row=rows(next.ports).find(r=>r.ports.some(p=>p.id===rightId));const i=row?.ports.findIndex(p=>p.id===rightId);if(!row||i<1)throw Error('No previous port in this row.');const shift=value-(bounds(row.ports[i]).left-bounds(row.ports[i-1]).right);for(const p of row.ports.slice(i))p.x=round(p.x+shift);return checked(next);}
function horizontal(s,ids,mode,distance,align){if(!['gap','pitch'].includes(mode)||!['left','center','right'].includes(align)||!Number.isFinite(distance)||distance<0)throw Error('Invalid horizontal layout.');const next=structuredClone(s),chosen=new Set(ids);for(const row of rows(next.ports.filter(p=>!chosen.size||chosen.has(p.id)))){const ps=row.ports;for(let i=1;i<ps.length;i++)ps[i].x=round(mode==='pitch'?ps[i-1].x+distance:bounds(ps[i-1]).right+distance+(ps[i].x-bounds(ps[i]).left));const left=Math.min(...ps.map(p=>bounds(p).left)),right=Math.max(...ps.map(p=>bounds(p).right)),margin=s.mounts?s.inset+s.mountDiameter/2+4+s.hardwareClearance:4;const shift=align==='left'?margin-left:align==='right'?s.width-margin-right:(s.width-left-right)/2;for(const p of ps)p.x=round(p.x+shift);}return checked(next);}
function stack(s,selectedId,count){if(!Number.isInteger(count)||count<1||count>11)throw Error('Choose 1 to 11 rack units.');const row=rows(s.ports).find(r=>r.ports.some(p=>p.id===selectedId))||rows(s.ports)[0];if(!row)throw Error('Add a row of connectors first.');if(row.ports.length*count>100)throw Error('Stacked panel would exceed 100 ports.');const next=structuredClone(s);next.units='rack';next.rackUnits=count;next.height=round(count*44.45-.8);let id=Math.max(...s.ports.map(p=>p.id))+1;next.ports=[];for(let r=0;r<count;r++)for(const p of row.ports){const q=structuredClone(p),dy=25+r*44.45-p.y;q.y=round(p.y+dy);q.labelY=round(p.labelY+dy);if(r){q.id=id++;q.label=(p.label.slice(0,33)+' R'+(r+1));}next.ports.push(q);}return checked(next);}
function autoFit(s,mode='gap',distance=1){if(!['gap','pitch'].includes(mode)||!Number.isFinite(distance)||distance<0)throw Error('Invalid spacing.');const next=structuredClone(s),kept=[],removed=[];const margin=s.mounts?s.inset+s.mountDiameter/2+4+s.hardwareClearance:4;
const footprint=p=>{const b=bounds(p),label=p.label.length*s.fontSize*.36;return {left:Math.min(b.left,p.x-label),right:Math.max(b.right,p.x+label)};};
for(const row of rows(next.ports)){let previous=null;for(const p of row.ports){const b=footprint(p),half=p.x-b.left;p.x=round(previous?(mode==='pitch'?previous.x+distance:footprint(previous).right+Math.max(1,distance)+half):margin+half);const trial={...next,ports:[...kept,p]};if(footprint(p).right>s.width-margin||P.portIssues(trial).some(i=>i.reasons.length)){removed.push(p.id);continue;}kept.push(p);previous=p;}}
next.ports=kept;return {state:P.validate(next),removed};}
const api={autoFit,bounds,rows,gaps,setGap,horizontal,stack};if(typeof module!=='undefined')module.exports=api;else root.Layout=api;
})(typeof window!=='undefined'?window:globalThis);
