(function(root){
'use strict';
const J=typeof module!=='undefined'?require('./joints.js'):root.Joints;
const presets={d:{name:'D-series · Ø24',shape:'circle',w:24,h:24,screws:true,sx:19,sy:24,sd:3.2,maxThickness:3},round:{name:'Round · custom',shape:'circle',w:9.5,h:9.5,screws:false,sx:19,sy:24,sd:3.2,maxThickness:0},rect:{name:'Rectangle · custom',shape:'rect',w:16,h:14,screws:false,sx:24,sy:0,sd:3.2,maxThickness:0}};
const port=(i,x)=>({id:i,type:'d',label:['MIC 01','MIC 02','LINE L','LINE R','AES IN','AES OUT'][i-1]||`PORT ${i}`,x,y:25,labelY:7,rotation:0,...presets.d});
function initial(){return {version:1,...J.defaults,name:'Studio patch panel',format:'19',units:'1',width:482.6,height:43.65,thickness:3,mounts:true,inset:8.75,mountDiameter:6.5,bodyColor:'#263334',labelColor:'#d7f6a3',fontSize:3.2,inlay:.6,bed:256,ports:Array.from({length:6},(_,i)=>port(i+1,51+(380.6/5)*i))};}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const n=x=>Math.round(x*10000)/10000;
function cutouts(p){const a=p.rotation*Math.PI/180,transform=(x,y)=>({x:p.x+x*Math.cos(a)-y*Math.sin(a),y:p.y+x*Math.sin(a)+y*Math.cos(a)});let c=[{...transform(0,0),shape:p.shape,w:p.w,h:p.shape==='circle'?p.w:p.h,rotation:p.rotation}];if(p.screws)for(const s of [-1,1])c.push({...transform(s*p.sx/2,s*p.sy/2),shape:'circle',w:p.sd,h:p.sd,rotation:0});return c;}
function mounts(s){if(!s.mounts)return [];const ys=s.height>65?[5.95,s.height-5.95]:[s.height/2];return [s.inset,s.width-s.inset].flatMap(x=>ys.map(y=>({x,y,shape:'circle',w:s.mountDiameter,h:s.mountDiameter,rotation:0})));}
function box(c){let a=c.rotation*Math.PI/180;const w=c.shape==='circle'?c.w:Math.abs(c.w*Math.cos(a))+Math.abs(c.h*Math.sin(a)),h=c.shape==='circle'?c.h:Math.abs(c.w*Math.sin(a))+Math.abs(c.h*Math.cos(a));return {x:c.x-w/2,y:c.y-h/2,w,h};}
function intersects(a,b,gap=0){return a.x<b.x+b.w+gap&&a.x+a.w+gap>b.x&&a.y<b.y+b.h+gap&&a.y+a.h+gap>b.y;}
function textBox(s,p){return {x:p.x-p.label.length*s.fontSize*.36,y:p.labelY-s.fontSize*.65,w:p.label.length*s.fontSize*.72,h:s.fontSize*1.3};}
function splitPlan(s){return J.plan(s,[...mounts(s),...s.ports.flatMap(cutouts)].map(box),s.ports.filter(p=>p.label).map(p=>textBox(s,p)));}
function rackEars(s,plan=splitPlan(s)){const depth=s.mounts?Math.max(s.reinforce?s.ribDepth:0,plan.seams.length?J.spec.keyDepth:0):0;const width=s.inset+s.mountDiameter/2+4;return {depth,width,total:s.thickness+depth,regions:depth?[{x:0,y:0,w:width,h:s.height},{x:s.width-width,y:0,w:width,h:s.height}]:[]};}
function warnings(s){const issues=[];const plan=splitPlan(s);if(plan.error)issues.push(plan.error);else if(!plan.enabled&&(s.width>s.bed||s.height>s.bed))issues.push('Panel exceeds the printer bed. Enable automatic splitting for rear dovetail snap keys.');if(s.ports.some(p=>p.maxThickness>0&&s.thickness>p.maxThickness))issues.push('Panel thickness exceeds a connector mounting limit. Reduce face thickness or check the exact part specification. Rear ribs do not increase the mounting face thickness.');if(s.width>200&&!s.reinforce)issues.push('Wide flat panels may flex. Enable rear strengthening ribs.');if(s.thickness<2.4)issues.push('Thin mounting face: check stiffness and fastener loading with your material.');if(s.inlay>=s.thickness)issues.push('Inlay depth must be less than panel thickness.');const inside=b=>b.x>=1&&b.y>=1&&b.x+b.w<=s.width-1&&b.y+b.h<=s.height-1;const groups=s.ports.map(p=>({p,boxes:cutouts(p).map(box)}));const mb=mounts(s).map(box),ears=rackEars(s,plan);for(const {p,boxes}of groups){if(boxes.some(b=>ears.regions.some(e=>intersects(b,e))))issues.push(`${p.label||"Unnamed port"}: cutout overlaps a solid rack mounting ear. Move this port inward before exporting.`);else if(boxes.some(b=>ears.regions.some(e=>intersects(b,e,s.hardwareClearance))))issues.push(`${p.label||"Unnamed port"}: check rear connector clearance beside the solid rack mounting ear; move the port inward if needed.`);if(boxes.some(b=>!inside(b)))issues.push(`${p.label||'Unnamed port'}: cutout is too close to or outside the panel edge.`);if(boxes.some(b=>mb.some(m=>intersects(b,m,1))))issues.push(`${p.label||'Unnamed port'}: cutout conflicts with a rack mounting hole.`);if(p.label){const t=textBox(s,p);if(!inside(t))issues.push(`${p.label}: lettering may extend beyond the panel edge.`);if([...groups.flatMap(g=>g.boxes),...mb].some(b=>intersects(t,b,.5)))issues.push(`${p.label}: lettering may overlap a cutout.`);}}
for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){if(groups[i].boxes.some(a=>groups[j].boxes.some(b=>intersects(a,b,1))))issues.push(`Ports ${i+1} and ${j+1}: cutouts overlap or have less than 1 mm clearance.`);if(groups[i].p.label&&groups[j].p.label&&intersects(textBox(s,groups[i].p),textBox(s,groups[j].p)))issues.push(`Ports ${i+1} and ${j+1}: labels may overlap.`);}return issues;}
function geometry(c,fill){return c.shape==='circle'?`<circle cx="${n(c.x)}" cy="${n(c.y)}" r="${n(c.w/2)}" fill="${fill}"/>`:`<rect x="${n(c.x-c.w/2)}" y="${n(c.y-c.h/2)}" width="${n(c.w)}" height="${n(c.h)}" transform="rotate(${c.rotation} ${c.x} ${c.y})" fill="${fill}"/>`;}
function svg(s,selected=null,download=false){const plan=splitPlan(s);return `<svg xmlns="http://www.w3.org/2000/svg" width="${s.width}mm" height="${s.height}mm" viewBox="${download?`0 0 ${s.width} ${s.height}`:`-8 -18 ${s.width+16} ${s.height+36}`}" role="img" aria-label="Front view of patch panel"><defs><mask id="panelMask"><rect width="${s.width}" height="${s.height}" fill="white"/>${[...mounts(s),...s.ports.flatMap(cutouts)].map(c=>geometry(c,'black')).join('')}</mask></defs><rect width="${s.width}" height="${s.height}" rx="2" fill="${s.bodyColor}" mask="url(#panelMask)"/>${!download?plan.seams.map(x=>`<rect x="${x-18}" y="0" width="36" height="${s.height}" fill="white" fill-opacity=".08" stroke="#999" stroke-width=".35" stroke-dasharray="1 1"/><path d="M${x} 0V${s.height}" stroke="#fff" stroke-width=".6" stroke-dasharray="2 1"/>`).join(''):''}${s.ports.map(p=>`<g data-port="${p.id}" tabindex="0" role="button" aria-label="Edit ${esc(p.label)}">${!download?`<rect x="${p.x-Math.max(p.w/2+5,16)}" y="${Math.min(p.labelY-4,p.y-p.h/2-5)}" width="${Math.max(p.w+10,32)}" height="${Math.max(p.y+p.h/2+5,p.labelY+4)-Math.min(p.labelY-4,p.y-p.h/2-5)}" rx="2" fill="transparent" stroke="${p.id===selected?'#eeeeee':'transparent'}" stroke-width=".6" stroke-dasharray="2 1.5"/>`:''}<text x="${p.x}" y="${p.labelY}" fill="${s.labelColor}" font-family="Liberation Sans,Arial,sans-serif" font-weight="bold" font-size="${s.fontSize}" text-anchor="middle" dominant-baseline="central">${esc(p.label)}</text></g>`).join('')}${!download?`<path d="M0 -8H${s.width} M0 -10V-6 M${s.width} -10V-6" stroke="#777777" stroke-width=".5"/><text x="${s.width/2}" y="-11" text-anchor="middle" font-family="Arial" font-size="4" fill="#555555">${s.width} mm</text>`:''}</svg>`;}
function scad(s,mode){s=J.settings(s);if(mode!=="tolerance"&&s.ports.some(p=>p.maxThickness>0&&s.thickness>p.maxThickness))throw Error('Face thickness exceeds a connector mounting limit. Reduce thickness or update the limit from its exact drawing.');const plan=splitPlan(s);const ears=rackEars(s,plan);if(mode!=="tolerance"&&s.ports.flatMap(cutouts).map(box).some(b=>ears.regions.some(e=>intersects(b,e))))throw Error("A connector cutout overlaps a solid rack mounting ear. Move the port inward before exporting.");if(mode!=="tolerance"&&plan.enabled&&plan.error)throw Error(plan.error);const shape=c=>`translate([${n(c.x)},${n(s.height-c.y)},-0.1]) linear_extrude(height=thickness+0.2) ${c.shape==='circle'?`circle(d=${c.w});`:`rotate(${-c.rotation}) square([${c.w},${c.h}],center=true);`}`;let output = `// PATCHLAB — ${s.name.replace(/[\r\n]/g,' ')}\n// Dimensions in mm. Front view +Z. Export body and labels separately.\n// Import both as parts of one object; preserve their shared coordinates.\n// Templates must be checked against your exact connector drawing.\npart = "assembly"; // [assembly, body, labels]\n$fn=96;\nthickness=${s.thickness};\ninlay=${s.inlay};\nassert(inlay > 0 && inlay < thickness,"Inlay must be smaller than panel thickness");\nmodule blank(){linear_extrude(height=thickness) hull(){for(x=[2,${s.width-2}],y=[2,${s.height-2}])translate([x,y])circle(r=2);}}\nmodule holes(){\n${[...mounts(s),...s.ports.flatMap(cutouts)].map(shape).join('\n')}\n}\nmodule lettering(){\n${s.ports.filter(p=>p.label).map(p=>`translate([${p.x},${n(s.height-p.labelY)},thickness-inlay]) linear_extrude(height=inlay) text(${JSON.stringify(p.label)},size=${s.fontSize},font="Liberation Sans:style=Bold",halign="center",valign="center");`).join('\n')}\n}\nmodule panel(){difference(){blank();holes();}}\nmodule labels(){intersection(){panel();lettering();}}\nmodule body(){difference(){panel();lettering();}}\nif(part=="body") body();\nelse if(part=="labels") labels();\nelse {color("${s.bodyColor}")body();color("${s.labelColor}")labels();}\n`;if(mode==="tolerance"||s.reinforce||(plan.enabled&&plan.seams.length)){output=output.slice(0,output.indexOf('if(part=="body")'));output=output.replace('[assembly, body, labels]','[assembly, body, labels, key, coupon, tolerance]');output+=reinforcementScad(s,plan)+J.scad(s,plan);}if(mode==="tolerance")output=output.replace('part = "assembly"','part = "tolerance"');return output;}

function reinforcementScad(s,plan){
 const ears=rackEars(s,plan);
 const keepouts=[...mounts(s),...s.ports.flatMap(cutouts)].map(box).map(b=>({x:b.x-s.hardwareClearance,y:s.height-b.y-b.h-s.hardwareClearance,w:b.w+2*s.hardwareClearance,h:b.h+2*s.hardwareClearance}));
 return `
module rack_ears(){
${ears.depth?`difference(){union(){for(x=[0,${s.width-ears.width}])translate([x,0,-${ears.depth}])cube([${ears.width},${s.height},${ears.depth+.05}]);}
${mounts(s).map(c=>`translate([${c.x},${n(s.height-c.y)},-${ears.depth+.1}])cylinder(h=${ears.depth+.2},d=${c.w});`).join("\n")}
}`:"// No rear backing needed."}
}
module reinforcement(){
${s.reinforce?`difference(){union(){for(y=[0,${s.height-s.ribWidth}])translate([0,y,-${s.ribDepth}])cube([${s.width},${s.ribWidth},${s.ribDepth+.05}]);for(x=[0,${s.width-s.ribWidth}])translate([x,0,-${s.ribDepth}])cube([${s.ribWidth},${s.height},${s.ribDepth+.05}]);}
${keepouts.map(b=>`translate([${b.x},${b.y},-${s.ribDepth+1}])cube([${b.w},${b.h},${s.ribDepth+2}]);`).join('\n')}
${plan.seams.map(x=>`translate([${x-18},-1,-${s.ribDepth+1}])cube([36,${s.height+2},${s.ribDepth+2}]);`).join('\n')}
}`:'// Ribs disabled.'}
}
`;
}


function rearSvg(s){const plan=splitPlan(s),pad=s.hardwareClearance??4;const boxes=[...mounts(s),...s.ports.flatMap(cutouts)].map(box);return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-8 -8 '+(s.width+16)+' '+(s.height+16)+'" role="img" aria-label="Rear view of strengthening ribs and dovetail channels"><defs><mask id="ribsMask"><rect width="'+s.width+'" height="'+s.height+'" fill="white"/>'+boxes.map(b=>'<rect x="'+(b.x-pad)+'" y="'+(b.y-pad)+'" width="'+(b.w+2*pad)+'" height="'+(b.h+2*pad)+'" fill="black"/>').join('')+plan.seams.map(x=>'<rect x="'+(x-18)+'" width="36" height="'+s.height+'" fill="black"/>').join('')+'</mask></defs><g transform="translate('+s.width+' 0) scale(-1 1)"><rect width="'+s.width+'" height="'+s.height+'" rx="2" fill="#333"/>'+[...mounts(s),...s.ports.flatMap(cutouts)].map(c=>geometry(c,'#eee')).join('')+(s.reinforce?'<g mask="url(#ribsMask)" fill="#999">'+[0,s.height-s.ribWidth].map(y=>'<rect y="'+y+'" width="'+s.width+'" height="'+s.ribWidth+'"/>').join('')+[0,s.width-s.ribWidth].map(x=>'<rect x="'+x+'" width="'+s.ribWidth+'" height="'+s.height+'"/>').join('')+'</g>':'')+plan.seams.map(x=>'<rect x="'+(x-18)+'" width="36" height="'+s.height+'" fill="#999"/>'+[-9,9].map(dx=>'<rect x="'+(x+dx-4)+'" y="3" width="8" height="'+(s.height-3)+'" fill="#222"/>').join('')+'<path d="M'+x+' 0V'+s.height+'" stroke="white" stroke-width=".5" stroke-dasharray="1 1"/>').join('')+rackEars(s,plan).regions.map(e=>'<rect x="'+e.x+'" y="0" width="'+e.w+'" height="'+e.h+'" fill="#bbb"/>').join('')+mounts(s).map(c=>geometry(c,'#eee')).join('')+'</g></svg>';}

function validate(s){if(!s||s.version!==1||!Array.isArray(s.ports)||s.ports.length>100)throw Error('Not a supported Patchlab project.');for(const [key,value]of Object.entries(J.defaults))if(s[key]===undefined)s[key]=value;if(typeof s.reinforce!=='boolean'||typeof s.autoSplit!=='boolean')throw Error('Invalid automatic splitting setting.');const ranges={bedMargin:[0,20],fitClearance:[.05,.6],ribDepth:[3,20],ribWidth:[2,6],hardwareClearance:[2,10],width:[50,1500],height:[20,500],thickness:[1,12],inset:[4,40],mountDiameter:[2,12],fontSize:[1.5,10],inlay:[.2,2],bed:[50,1500]};for(const [k,[min,max]]of Object.entries(ranges))if(typeof s[k]!=='number'||!Number.isFinite(s[k])||s[k]<min||s[k]>max)throw Error(`Invalid ${k}.`);if(typeof s.name!=='string'||s.name.length>80||typeof s.mounts!=='boolean'||!['19','10','custom'].includes(s.format)||!['1','2','3','custom'].includes(s.units))throw Error('Invalid project settings.');for(const c of ['bodyColor','labelColor'])if(!/^#[0-9a-f]{6}$/i.test(s[c]))throw Error('Invalid color.');const ids=new Set();for(const p of s.ports){if(p.maxThickness===undefined)p.maxThickness=presets[p.type]?.maxThickness??0;if(typeof p.maxThickness!=='number'||!Number.isFinite(p.maxThickness)||p.maxThickness<0||p.maxThickness>12)throw Error('Invalid connector mounting limit.');if(!Number.isInteger(p.id)||ids.has(p.id)||!presets[p.type]||!['circle','rect'].includes(p.shape)||typeof p.label!=='string'||p.label.length>40||typeof p.screws!=='boolean')throw Error('Invalid connector.');ids.add(p.id);for(const k of ['x','y','labelY','rotation','w','h','sx','sy','sd'])if(typeof p[k]!=='number'||!Number.isFinite(p[k])||Math.abs(p[k])>2000)throw Error('Invalid connector dimension.');if(p.w<=0||p.h<=0||p.sd<=0||p.sx<0||p.sy<0)throw Error('Connector dimensions must be positive.');}return s;}
function arrange(s){if(!s.ports.length)return;const margin=Math.max(28,...s.ports.map(p=>Math.max(...cutouts({...p,x:0,y:0}).map(box).map(b=>Math.max(Math.abs(b.x),Math.abs(b.x+b.w))))+16));s.ports.forEach((p,i)=>p.x=n(s.ports.length===1?s.width/2:margin+i*(s.width-2*margin)/(s.ports.length-1)));}
function batchEdit(s,ids,patch){
const next=JSON.parse(JSON.stringify(s)),picked=new Set(ids);let index=0;
for(const p of next.ports){if(!picked.has(p.id))continue;
 if(patch.type){if(!presets[patch.type])throw Error('Unknown connector template.');Object.assign(p,presets[patch.type],{type:patch.type});}
 for(const key of ['y','labelY','w','h','rotation','sx','sy','sd','screws','maxThickness'])if(Object.hasOwn(patch,key))p[key]=patch[key];
 if(Object.hasOwn(patch,'label'))p.label=patch.label.replaceAll('{n}',String((patch.start??1)+index).padStart(2,'0'));
 if(p.label.length>40)throw Error('Generated port names must be 40 characters or fewer.');index++;
}return validate(next);
}
const api={rackEars,rearSvg,splitPlan,batchEdit,presets,initial,port,esc,cutouts,mounts,warnings,svg,scad,validate,arrange};if(typeof module!=='undefined')module.exports=api;else root.Panel=api;
})(typeof window!=='undefined'?window:globalThis);
