const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('./model.js');
test('default project validates, roundtrips, and auto-splits',()=>{const s=M.initial();assert.deepEqual(M.validate(JSON.parse(JSON.stringify(s))),s);assert.equal(M.warnings(s).length,0);assert.equal(M.splitPlan(s).segments.length,2);});
test('rotated diagonal screw pattern follows the cutout',()=>{const p=M.port(1,50);p.rotation=90;const c=M.cutouts(p);assert.equal(c.length,3);assert.ok(Math.abs(c[1].x-62)<1e-9);assert.ok(Math.abs(c[1].y-15.5)<1e-9);});
test('collision and boundary checks catch impossible layouts',()=>{const s=M.initial();s.ports[1].x=s.ports[0].x;assert.ok(M.warnings(s).some(x=>/overlap/.test(x)));s.ports[0].x=0;assert.ok(M.warnings(s).some(x=>/outside/.test(x)));});
test('spacing uses actual panel width and handles a single port',()=>{const s=M.initial();s.width=254;M.arrange(s);assert.ok(s.ports.every(p=>p.x>20&&p.x<234));s.ports=s.ports.slice(0,1);M.arrange(s);assert.equal(s.ports[0].x,127);});
test('SVG escapes labels and maintains physical dimensions',()=>{const s=M.initial();s.ports[0].label='<script>"&';const out=M.svg(s,null,true);assert.ok(out.includes('width="482.6mm"'));assert.ok(!out.includes('<script>'));assert.ok(out.includes('&lt;script&gt;'));});
test('SCAD shares material coordinates and cuts inlay from body',()=>{const s=M.initial();s.ports[0].label='A "B" \\ C';const out=M.scad(s);assert.ok(out.includes(JSON.stringify(s.ports[0].label)));assert.match(out,/module labels\(\)\{intersection\(\)\{panel\(\);lettering\(\);\}\}/);assert.match(out,/module body\(\)\{difference\(\)\{panel\(\);lettering\(\);\}\}/);assert.match(out,/translate\(\[51,36.65,thickness-inlay\]\)/);});
test('imports reject unsafe values and duplicate IDs',()=>{for(const mutate of [s=>s.width=-1,s=>s.ports[0].w=NaN,s=>s.ports[0].label=null,s=>s.ports[1].id=s.ports[0].id,s=>s.bodyColor='red; script']){const s=M.initial();mutate(s);assert.throws(()=>M.validate(s));}});
test('batch edits preserve other ports and number selected ports in lineup order',()=>{const s=M.initial();const out=M.batchEdit(s,[4,2],{type:'round',w:12,label:'INPUT {n}',start:5,screws:false});assert.equal(out.ports[1].label,'INPUT 05');assert.equal(out.ports[3].label,'INPUT 06');assert.equal(out.ports[1].w,12);assert.equal(out.ports[1].screws,false);assert.equal(out.ports[1].x,s.ports[1].x);assert.deepEqual(out.ports[0],s.ports[0]);assert.equal(s.ports[1].type,'d');});
test('invalid batch edit is atomic and does not modify the project',()=>{const s=M.initial(),before=JSON.stringify(s);assert.throws(()=>M.batchEdit(s,[1,2],{w:-2}));assert.equal(JSON.stringify(s),before);assert.deepEqual(M.batchEdit(s,[1,2],{}),s);});

test('split planner respects bed margins, connector keepouts and labels',()=>{const s=M.initial(),p=M.splitPlan(s);assert.equal(p.error,null);assert.ok(p.segments.every(x=>x.width<=s.bed-2*s.bedMargin+1e-6));assert.ok(Math.abs(p.segments.reduce((n,x)=>n+x.width,0)-s.width)<1e-6);for(const x of p.seams)for(const port of s.ports)assert.ok(Math.abs(x-port.x)>port.w/2+18+s.hardwareClearance);});
test('crowded seams and tall panels block unsafe split exports',()=>{const s=M.initial();s.height=300;assert.match(M.splitPlan(s).error,/height/);assert.throws(()=>M.scad(s));assert.ok(M.scad(s,'tolerance').includes('part = "tolerance"'));s.height=43.65;s.ports=Array.from({length:16},(_,i)=>M.port(i+1,15+i*30));assert.ok(M.splitPlan(s).error);assert.throws(()=>M.scad(s));});
test('legacy projects migrate reinforcement and clearance settings',()=>{const s=M.initial();for(const k of ['autoSplit','bedMargin','fitClearance','reinforce','ribDepth','ribWidth','hardwareClearance'])delete s[k];delete s.ports[0].maxThickness;const v=M.validate(s);assert.equal(v.fitClearance,.15);assert.equal(v.ribDepth,8);assert.equal(v.ports[0].maxThickness,3);});
test('invalid fit settings are rejected and mounting thickness is checked',()=>{for(const [k,value]of [['fitClearance',0],['ribDepth',100],['reinforce','true'],['bedMargin',-1]]){const s=M.initial();s[k]=value;assert.throws(()=>M.validate(s));}const s=M.initial();s.thickness=4;assert.ok(M.warnings(s).some(w=>w.includes('mounting limit')));assert.throws(()=>M.scad(s),/mounting limit/);});
test('reinforcement, fit test and per-segment exports use shared geometry',()=>{const s=M.initial(),out=M.scad(s);assert.match(out,/module reinforcement/);assert.match(out,/module snap_key/);assert.match(out,/rail_profile\(clearance\)/);assert.match(out,/module face_down/);assert.ok(M.scad(s,'tolerance').includes('part = "tolerance"'));s.width=150;s.ports=[];assert.equal(M.splitPlan(s).segments.length,1);assert.ok(M.scad(s).includes('module reinforcement'));assert.ok(M.rearSvg(s).includes('Rear view'));});
const STL=require('./stl-export.js');
test('STL print kit includes paired materials and one reusable key',()=>{const s=M.initial(),jobs=STL.jobsFor(s,M);assert.equal(jobs.length,5);assert.deepEqual(jobs.map(j=>j.name),['section-01-body.stl','section-01-labels.stl','section-02-body.stl','section-02-labels.stl','joining-key-print-1-copies.stl']);assert.ok(jobs[2].source.includes('segment = 2;'));s.ports.forEach(p=>p.label='');assert.equal(STL.jobsFor(s,M).length,3);s.height=300;assert.throws(()=>STL.jobsFor(s,M));});
test('ZIP export stores exact bytes with CRC and directory offsets',async()=>{assert.equal(STL.crc32(new TextEncoder().encode('123456789')),0xcbf43926);const bytes=new Uint8Array(await STL.zip([{name:'part.stl',bytes:new Uint8Array([0,1,255])},{name:'note.txt',bytes:'hello'}]).arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(18,true),3);assert.deepEqual(Array.from(bytes.slice(38,41)),[0,1,255]);const end=bytes.length-22;assert.equal(v.getUint32(end,true),0x06054b50);assert.equal(v.getUint16(end+10,true),2);assert.equal(v.getUint32(v.getUint32(end+16,true),true),0x02014b50);});

test('10-inch panel on 256 mm bed explains margin conflict and exports at 1 mm margin',()=>{const s=M.initial();s.width=254;s.ports=Array.from({length:7},(_,i)=>M.port(i+1,28+i*33));assert.match(M.splitPlan(s).error,/246 mm usable width/);assert.match(M.splitPlan(s).error,/1 mm or less/);assert.throws(()=>STL.jobsFor(s,M));s.bedMargin=1;assert.equal(M.splitPlan(s).error,null);assert.equal(M.splitPlan(s).segments.length,1);assert.deepEqual(STL.jobsFor(s,M).map(j=>j.name),['panel-body.stl','panel-labels.stl']);});

test('rack ears have uniform backing to the deepest rear feature',()=>{const s=M.initial();let e=M.rackEars(s);assert.equal(e.depth,8.5);assert.equal(e.total,11.5);assert.equal(e.width,16);assert.equal(e.regions.length,2);s.ribDepth=12;assert.equal(M.rackEars(s).total,15);s.width=150;s.ports=[];s.ribDepth=8;assert.equal(M.rackEars(s).total,11);s.reinforce=false;assert.equal(M.rackEars(s).depth,0);s.width=482.6;assert.equal(M.rackEars(s).depth,8.5);s.mounts=false;assert.equal(M.rackEars(s).regions.length,0);});
test('solid ears protect connector face thickness and reject intersecting ports',()=>{const s=M.initial();assert.equal(s.thickness,3);assert.match(M.scad(s),/module rack_ears/);s.ports[0].x=25;assert.ok(M.warnings(s).some(w=>/cutout overlaps a solid rack/.test(w)));assert.throws(()=>M.scad(s),/solid rack mounting ear/);assert.doesNotThrow(()=>M.scad(s,'tolerance'));s.ports[0].x=28;assert.doesNotThrow(()=>M.scad(s));assert.ok(M.warnings(s).some(w=>/rear connector clearance/.test(w)));});

const MF=require('./three-mf.js');
function tetraSTL(){const points=[[0,0,0],[1,0,0],[0,1,0],[0,0,1]],faces=[[0,2,1],[0,1,3],[0,3,2],[1,2,3]],bytes=new Uint8Array(284),v=new DataView(bytes.buffer);v.setUint32(80,4,true);faces.forEach((f,i)=>f.forEach((p,j)=>points[p].forEach((x,a)=>v.setFloat32(84+i*50+12+j*12+a*4,x,true))));return bytes;}
test('3MF mesh preserves coordinates and shares vertices across triangles',()=>{const xml=MF.mesh(tetraSTL());assert.equal((xml.match(/<vertex /g)||[]).length,4);assert.equal((xml.match(/<triangle /g)||[]).length,4);assert.match(xml,/<vertex x="0" y="0" z="1"/);assert.throws(()=>MF.mesh(new Uint8Array(12)));const bad=tetraSTL();new DataView(bad.buffer).setFloat32(96,NaN,true);assert.throws(()=>MF.mesh(bad),/coordinate/);});
test('3MF groups each body and labels without moving components and instances every key',()=>{const s=M.initial();s.width=800;s.ports=[];const plan=M.splitPlan(s);const inputs=STL.jobsFor(s,M).map(j=>({name:j.name,bytes:tetraSTL()}));for(let i=0;i<plan.segments.length;i++)inputs.push({name:'section-'+String(i+1).padStart(2,'0')+'-labels.stl',bytes:tetraSTL()});s.name='A & "B" <panel>';const files=MF.filesFor(inputs,s,M),xml=files.find(f=>f.name.endsWith('.model')).bytes;assert.equal((xml.match(/<item /g)||[]).length,plan.segments.length+plan.seams.length);assert.equal((xml.match(/<components>/g)||[]).length,plan.segments.length);assert.equal((xml.match(/<component objectid="\d+"\/>/g)||[]).length,2*plan.segments.length);assert.match(xml,/A &amp; &quot;B&quot; &lt;panel&gt;/);assert.match(xml,/unit="millimeter"/);assert.match(xml,/pindex="1"/);assert.equal(files.length,3);assert.match(files[1].bytes,/Target="\/3D\/3dmodel.model"/);assert.throws(()=>MF.filesFor([],s,M),/Missing section/);});
test('3MF supports blank labels and one unsplit section',()=>{const s=M.initial();s.width=150;s.ports=[];const files=MF.filesFor(STL.jobsFor(s,M).map(j=>({name:j.name,bytes:tetraSTL()})),s,M);const xml=files[2].bytes;assert.equal((xml.match(/<component /g)||[]).length,1);assert.equal((xml.match(/<item /g)||[]).length,1);});
